version: '3'

services:
  kafka-server:
    container_name: kafka-server
    privileged: true
    build: ./kafka-server
    ports:
      - "10022:22"
      - "9092:9092"
      - "2181:2181"
    stdin_open: true
    tty: true
  kafka-client:
    container_name: kafka-client
    build: ./kafka-client
    ports:
      - "20022:22"
    stdin_open: true
    tty: true